// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 13,
  states: "$nQVQPOOOeQPO'#C_OjQPO'#CiO!OQPO'#CcOOQO'#Ci'#CiOOQO'#Ce'#CeQVQPOOO!TQPO,58yO!YQPO,58{O!_QPO,58}OOQO-E6c-E6cOOQO1G.e1G.eO!gQQO1G.gO!lQPO'#CfO!qQPO1G.iO!yQPO1G.iO#_QPO7+$ROOQO,59Q,59QOOQO-E6d-E6dO!yQPO7+$TO#dQPO'#CbOOQO7+$T7+$TO#iQPO<<GmOOQO<<Go<<GoO#nQPO,58|O!yQPOAN=XOOQO1G.h1G.hOOQOG22sG22s",
  stateData: "#s~OPOS~OSQOWRO^POaSO~OSVO~O_WOS]XW]XZ]X^]Xa]X~OSXO~O^ZO~OS[O~Oa_Od]O~O``O~OSaO~OacOd]O~ObdOSUPWUPZUP^UPaUP~OSfO~OShO~OaiO~OcjO~O",
  goto: "|^PPP_P_c_PlrPPxTSOUQe_QgcRkiQUORYUQ^XRb^TTOU",
  nodeNames: "⚠ LineComment Program TitleExpression String InteractionExpression AnnotationExpression ActorExpression Actor",
  maxTerm: 20,
  skippedNodes: [0,1],
  repeatNodeCount: 2,
  tokenData: "&x~R^YZ}]^}pq!Yst!n|}!y}!O#O!Q![!Y!_!`#c!c!}!Y!}#O#n#P#Q#s#R#S!Y#T#U#x#U#o!Y~!SQa~YZ}]^}~!_TS~pq!Y!Q![!Y!c!}!Y#R#S!Y#T#o!Y~!sQP~OY!nZ~!n~#OOd~R#RP}!O#UR#ZP_P!`!a#^Q#cO`Q~#fP!_!`#i~#nO^~~#sOb~~#xOc~~#}VS~pq!Y!Q![!Y!c!}!Y#R#S!Y#T#V!Y#V#W$d#W#o!Y~$iVS~pq!Y!Q![!Y!c!}!Y#R#S!Y#T#h!Y#h#i%O#i#o!Y~%TVS~pq!Y!Q![!Y!c!}!Y#R#S!Y#T#c!Y#c#d%j#d#o!Y~%oVS~pq!Y!Q![!Y!c!}!Y#R#S!Y#T#f!Y#f#g&U#g#o!Y~&ZWS~pq!Y!Q![!Y![!]&s!c!}!Y#R#S!Y#T#g!Y#g#h&U#h#o!Y~&xOW~",
  tokenizers: [0, 1],
  topRules: {"Program":[0,2]},
  tokenPrec: 0
})
