// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Program = 2,
  TitleExpression = 3,
  String = 4,
  InteractionExpression = 5,
  AnnotationExpression = 6,
  ActorExpression = 7,
  Actor = 8
